#import "SCGPSViewController.h"
@implementation SCGPSViewController
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView{return 2;}
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{return section==0?6:5;}
- (NSString*)tableView:(UITableView*)tableView titleForHeaderInSection:(NSInteger)section{return section==0?@"GPS":@"Quick Locations";}
- (UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)i{ if(i.section==0){ if(i.row==0)return[self switchCellWithTitle:@"Bật GPS Spoof" on:self.config.geoEnabled action:@selector(toggle:)]; NSArray*t=@[@"Latitude",@"Longitude",@"Altitude",@"Accuracy",@"Heading"]; NSArray*v=@[@(self.config.latitude),@(self.config.longitude),@(self.config.altitude),@(self.config.horizontalAccuracy),@(self.config.heading)]; UITableViewCell*c=[self cellWithTitle:t[i.row-1] detail:nil]; c.accessoryView=[self textFieldWithText:[v[i.row-1] description] placeholder:@"" tag:200+i.row keyboard:UIKeyboardTypeDecimalPad]; return c;} NSArray*n=@[@"Hà Nội",@"TP.HCM",@"Đà Nẵng",@"New York",@"Tokyo"]; return[self cellWithTitle:n[i.row] detail:@""]; }
- (void)tableView:(UITableView*)tableView didSelectRowAtIndexPath:(NSIndexPath*)i{ if(i.section!=1)return; NSArray*c=@[@[@21.0285,@105.8542],@[@10.8231,@106.6297],@[@16.0471,@108.2068],@[@40.7128,@-74.0060],@[@35.6762,@139.6503]]; self.config.latitude=[c[i.row][0] doubleValue]; self.config.longitude=[c[i.row][1] doubleValue]; [self.config save]; [tableView reloadData]; }
- (void)saveAndReload{ for(UITableViewCell*c in self.tableView.visibleCells) if([c.accessoryView isKindOfClass:UITextField.class]){UITextField*t=(id)c.accessoryView; double v=t.text.doubleValue; if(t.tag==201)self.config.latitude=v; if(t.tag==202)self.config.longitude=v; if(t.tag==203)self.config.altitude=v; if(t.tag==204)self.config.horizontalAccuracy=v; if(t.tag==205)self.config.heading=v;} [self.config save];}
- (void)toggle:(UISwitch*)s{self.config.geoEnabled=s.on;[self.config save];}
@end
