include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = iOSSpoofPrefs
iOSSpoofPrefs_FILES = SCRootListController.m ../src/SCDevicePresets.m
iOSSpoofPrefs_CFLAGS = -fobjc-arc
iOSSpoofPrefs_FRAMEWORKS = UIKit Foundation Preferences
iOSSpoofPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
